version: "3"
services:
  mysql:
    container_name: mysql-5.7
    image: mysql:5.7.38
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    ports:
      - "3306:3306"
    command:
      - "--default-authentication-plugin=mysql_native_password"
    volumes:
      - /root/lib/mysql/:/var/lib/mysql/
