version: "3.8"

services:
  udcp_collect:
    image: hub.deepin.com/wuhan_udcp/udcp_collect/api:pre-amd64
    privileged: true
    volumes:
      - /opt/udcp/udcp_collect/hardware_information/:/service/data/
      - /sbin/dmidecode:/sbin/dmidecode
      - /dev/mem:/dev/mem
    cap_add:
      - ALL
    command:
      - "/service/api"
    logging:
      options:
        max-size: 10m
        max-file: 3
      
      
